trabalho_2/prototipo/SGPF/Controllers/CFController.cs
using System.Web.Mvc;

namespace SGPF.Controllers
{
    [Authorize]
    public class CFController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ComissionDispatch()
        {
            return View();
        }

        public ActionResult ReportProjectInfo()
        {
            return View();
        }

        public ActionResult ReportProjectPayment()
        {
            return View();
        }
    }
}

trabalho_2/prototipo/SGPF/Controllers/GCController.cs
using System.Web.Mvc;

namespace SGPF.Controllers
{
    public class GCController : Controller
    {
        //
        // GET: /GC/

        public ActionResult Index()
        {
            return View();
        }
    }
}

trabalho_2/prototipo/SGPF/Controllers/GFController.cs
using System.Web.Mvc;

namespace SGPF.Controllers
{
    public class GFController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Technicalreport()
        {
            return View();
        }

        public ActionResult PaymentRealization()
        {
            return View();
        }

        public ActionResult ProjectReinforcement()
        {
            return View();
        }
    }
}

trabalho_2/prototipo/SGPF/Controllers/HomeController.cs
using System.Web.Mvc;

namespace SGPF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Sistema de gestão de projectos de financiamento";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

trabalho_2/prototipo/SGPF/Controllers/TFController.cs
using System.Web.Mvc;

namespace SGPF.Controllers
{
    public class TFController : Controller
    {
        //
        // GET: /TF/

        public ActionResult Index()
        {
            return View();
        }
    }
}

trabalho_2/prototipo/SGPF/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>@ViewBag.Message</h2>

Protótipo da aplicação

@if (Request.IsAuthenticated)
{

    if (Roles.IsUserInRole(User.Identity.Name, "GestorContactos"))
    {
        <div>
            @Html.ActionLink("Área da Comissão Financiamento","Index","CF")
        </div>
    }

    if (User.IsInRole("GestorContactos"))
    {
        <div>
            @Html.ActionLink("Área do Gestor de Contacto", "Index", "GC")
        </div>
    }

    if (User.IsInRole("GestorFinanciamento"))
    {
        <div>
            @Html.ActionLink("Área do Gestor de Financiamentos", "Index", "GF")
        </div>
    }

    if (User.IsInRole("Tecnico"))
    {
        <div>
            @Html.ActionLink("Área do Tecnico de Financiamento", "Index", "TF")
        </div>
    }
}