trabalho_2/prototipo/SGPF/Controllers/AnexoController.cs
using System;
using System.Web.Mvc;
using SGPF.EntityDB;
using SGPF.Services;

namespace SGPF.Controllers
{
    public class AnexoController : Controller
    {
        private readonly AnexoDaoService Dao = AnexoDaoService.GetInstance();

        public ViewResult Index()
        {
            return View(Dao.GetAll());
        }

        //
        // GET: /Anexo/Details/5

        public ViewResult Details(int id)
        {
            var a = Dao.Read(id);

            if (User.IsInRole("Tecnico"))
            {
                return View("DetailsParecer", a as Parecer );

            }
            
            if (User.IsInRole("Comissao"))
            {
                return View("DetailsDespacho", a as Despacho);

            }

            return View(a);
        }

        //
        // GET: /Project/Create

        public ActionResult Create()
        {
            if (User.IsInRole("Tecnico"))
            {
                return View("CreateParecer");
            }

            if (User.IsInRole("Comissao"))
            {
                return View("CreateDespacho");
            }

            return View();
        }

        //
        // POST: /Project/Create

        [HttpPost]
        public ActionResult Create(Anexo a)
        {
            if (ModelState.IsValid)
            {
                Dao.Create(a);
                return RedirectToAction("Index");
            }

            return View(a);
        }

        [HttpPost]
        public ActionResult CreateDespacho(Despacho a)
        {
            if (ModelState.IsValid)
            {
                Dao.Create(a);
                return RedirectToAction("Index");
            }

            return View(a);
        }

        [HttpPost]
        public ActionResult CreateParecer(Parecer a)
        {
            if (ModelState.IsValid)
            {
                Dao.Create(a);
                return RedirectToAction("Index");
            }

            return View(a);
        }
    }
}

trabalho_2/prototipo/SGPF/Controllers/ProjectController.cs
using System;
using System.Web.Mvc;
using System.Web.Security;
using SGPF.EntityDB;
using SGPF.Services;

namespace SGPF.Controllers
{
    public class ProjectController : Controller
    {
        private static readonly ProjectDaoService Dao = ProjectDaoService.GetInstance();

        [HttpPost]
        public ViewResult Suspend(int id)
        {
            var p = Dao.Read(id);
            
            p.Suspenso = !p.Suspenso;
            Dao.Update(p);

            return View("Details",p);
        }

        [HttpPost]
        public ViewResult Search(String description)
        {
            return View("Index", Dao.GetAll(description));
        }

        //
        // GET: /Project/

        public ViewResult Index()
        {
            return View(Dao.GetAll());
        }

        //
        // GET: /Project/Details/5

        public ViewResult Details(int id)
        {
            Projecto projectmodel = Dao.Read(id);
            return View(projectmodel);
        }

        //
        // GET: /Project/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Project/Create

        [HttpPost]
        public ActionResult Create(Projecto projectmodel)
        {
            if (ModelState.IsValid)
            {
                Dao.Create(projectmodel);
                return RedirectToAction("Index");
            }

            return View(projectmodel);
        }

        //
        // GET: /Project/Edit/5

        public ActionResult Edit(int id)
        {
            Projecto projectmodel = Dao.Read(id);
            return View(projectmodel);
        }

        //
        // POST: /Project/Edit/5

        [HttpPost]
        public ActionResult Edit(Projecto projectmodel)
        {
            if (ModelState.IsValid)
            {
                Dao.Update(projectmodel);
                return RedirectToAction("Index");
            }

            return View(projectmodel);
        }

        //
        // GET: /Project/Delete/5

        public ActionResult Delete(int id)
        {
            return View(Dao.Read(id));
        }

        //
        // POST: /Project/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Dao.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

trabalho_2/prototipo/SGPF/Views/Shared/AnexosPartialView.cshtml
<p>
    @Html.ActionLink("Criar novo anexo","Create","Anexo")
</p>
<p>
    @Html.ActionLink("Ver anexos","Index","Anexo")
</p>

trabalho_2/prototipo/SGPF/Views/Shared/Search.cshtml
@if (ViewBag.ControllerName != null)
{
    String name = ViewBag.ControllerName;
    using (Html.BeginForm("Search", name))
    {
        <div>
            <fieldset>
                <legend>@ViewBag.SearchName</legend>
                <div class="editor-label">
                    @Html.Label("Descrição: ")
                </div>
                <div class="editor-field">
                    @Html.TextArea("description")
                </div>
                <p>
                    <input type="submit" value="Pesquisar" />
                </p>
            </fieldset>
        </div>
    }
}

trabalho_2/prototipo/SGPF/Views/Shared/SuspendResumeProject.cshtml
@model SGPF.EntityDB.Projecto

@if(Model!=null)
{
    using (Html.BeginForm("Suspend", "Project", FormMethod.Post))
    {
        <div>
            <fieldset>
                @Html.Hidden("id",Model.Id)

                <legend>@ViewBag.SearchName</legend>
                <div class="editor-label">
                    @Html.Label("Suspenso?")
                </div>
                <div class="editor-field">
                    @Html.CheckBox("toggle",Model.Suspenso)
                </div>
                <p>
                    <input type="submit" value="Toggle" />
                </p>
            </fieldset>
        </div>
    }
}

trabalho_2/prototipo/SGPF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>Sistema de gestão de projectos de financiamento</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

trabalho_2/prototipo/SGPF/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}